version: '3.8'

services:
  # User Service
  user-service:
    # IMPORTANT: Use the image name you pushed to your registry
    image: your-docker-repo/user-service:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/user_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mysql_db

  # Schedule Service
  schedule-service:
    image: your-docker-repo/schedule-service:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/schedule_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - mysql_db

  # Booking Service
  booking-service:
    image: your-docker-repo/booking-service:latest
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql_db:3306/booking_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      # This URL uses the service name 'schedule-service' defined in this file
      - SCHEDULE_SERVICE_URL=http://schedule-service:8082/api/schedules
    depends_on:
      - mysql_db
      - schedule-service

  # MySQL Database
  mysql_db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=user_db # Creates the first DB automatically
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
