global:
  scrape_interval: 15s # How frequently to scrape targets

scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8081']

  - job_name: 'schedule-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['schedule-service:8082']

  - job_name: 'booking-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['booking-service:8083']
