apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service # This must match the labels in the deployment.yaml
  ports:
    - protocol: TCP
      port: 80 # The port the service will be available on inside the cluster
      targetPort: 8081 # The port the container is running on
  type: ClusterIP # Only expose the service inside the cluster
